services:
  popit:
    build: .
    volumes_from:
    - redis
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      REDIS_URI: unix:///tmp/redis.sock
      NODE_ENV: production
      SSL_PRIV: $SSL_PRIV
      SSL_CERT: $SSL_CERT
    ports:
    - "$HTTPS_PORT:3000/tcp"
    restart: always
  redis:
    image: redislabs/rejson:2.8.4
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --unixsocket /tmp/redis.sock --unixsocketperm 666 --appendonly yes
    volumes:
    - /tmp
    - redis-data:/data

volumes:
  redis-data:
