version: '3'

services:
  popit:
    build: .
    volumes_from:
    - redis
    volumes:
    - /etc/letsencrypt:/home/app/ssl:ro
    environment:
      REDIS_URI: unix:///tmp/redis.sock
      NODE_ENV: production
      SSL_PRIV: /home/app/ssl/live/popit.librespeak.ru/privkey.pem
      SSL_PUB: /home/app/ssl/live/popit.librespeak.ru/fullchain.pem
    ports:
    - "8443:3000/tcp"
    restart: always
  redis:
    image: redislabs/rejson:1.0.7
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --unixsocket /tmp/redis.sock --unixsocketperm 666 --appendonly yes
    volumes:
    - /tmp
    - redis-data:/data

volumes:
  redis-data:
